#pragma once

#include <PioHandler.hpp>
#include <DmaHandler.hpp>
#include <stdio.h>
#include <array>
#include <functional>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"

#include "AudioInterface.hpp"

//the header generated by the PIO assembler containing the assembled program and
//various helper functions for loading the program
#include "audio_device.pio.h"

class AudioDevice;

class IRQHandler
{
private:
    static IRQHandler * instance;

    IRQHandler()
    {
        instance = this;
        n_devices = 0;
    }

    std::array<std::function<bool(void)>, 16> callbacks;

    int n_devices;

    void IRQ_handler_local();
public:

    IRQHandler(IRQHandler &handler_) = delete;

    void operator=(const IRQHandler &hanlder_) = delete;

    static void IRQ_handler_static()
    {
        instance->IRQ_handler_local();
    }

    static IRQHandler * getIRQHandler()
    {
        if (instance == nullptr)
        {
            return new IRQHandler();
        }
        return instance;
    }

    template<typename T>
    void registerDevice(T *obj, bool (T::*func)(void))
    {
        if (n_devices < 8)
        {
            callbacks[n_devices] = std::bind(func, obj);
            n_devices++;
        }
    }

};

IRQHandler * IRQHandler::instance = nullptr;

class AudioDevice
{
private:
    //----------HARDWARE DATA--------------

    struct Pins
    {
        uint data;
        uint lck;
        //bck is lck+1
    };
    Pins pins;
    
    PioHandler pio;
    
    //dma channel numbers

    DmaHandler dma_buffer;
    DmaHandler dma_control;

    //-----------------------------------
    //--------AUDIO BUFFERS AND CONTROLS---
    static const size_t BUFFSIZE = 1024;
    struct Buffer    //MAYBE REMOVE
    {
        uint32_t A[BUFFSIZE];
        uint32_t B[BUFFSIZE];
        uint32_t C[BUFFSIZE];
    };

    struct BufferPointers
    {
        uint32_t* A;
        uint32_t* B;
        uint32_t* C;
    };
    BufferPointers buffer_ptrs;
    //!!!!!!!!!!VARIABLE BUFFER SIZE
    Buffer buffer;
    uint32_t *buffer_start_pointer; //we will provide this to the DMA

    volatile bool buffer_update_flag = false;

    uint64_t chunkcount = 0; //number of audio buffers outputted from this device

    const uint64_t SPS = 45045;
    const int maxamp = 32767 / 2.5;

    AudioSource * source;
    bool useCallback = false;
    //------------INTERRUPT HANDLER---------
    IRQHandler * IRQ_handler_ptr;

public: //public types
    enum class DeviceMode {
        MONO,
        STEREO
    };

    enum class ChannelMode {
        MONO,
        LEFT,
        RIGHT
    };

    struct ChannelInfo
    {
        uint channel_num;
        ChannelMode chmode;
        uint64_t chunk;
        uint64_t sample;
        uint64_t SPS;
    };

    struct DeviceInfo
    {
        uint64_t SPS;
        DeviceMode mode;
        size_t buffsize;
        int maxamp;
    };
    

private:
    //channel setup
    DeviceMode mode;
    //virtual channels
    uint channel_num;

//---------PRIVATE FUNCTIONS------------
    //init functions
    inline void arm_dma_channels_chained_irq();
    void init_buffers();

    //utility

    inline uint32_t int16_to_uint32(int16_t val){
        return val << 16;
    }

public: //public methods
    AudioDevice();
    AudioDevice(uint dataPin, uint lckPin, DeviceMode mode_, uint channels, IRQHandler * irq_h_ptr);
    ~AudioDevice();

    //factory functions
    static AudioDevice createAudioDevice(uint dataPin, uint lckPin, DeviceMode mode, uint channels);

    void setSource(AudioSource *source_);

    //public init, returns true uppon successful initialization
    bool initialize();

    //update audio device, returns true if an update has been performed
    bool update();

    bool confirm_interrupt();

    void writeAudio(int i, int16_t value, ChannelMode mode);

    DeviceInfo getDeviceInfo()
    {
        return DeviceInfo{SPS,mode,BUFFSIZE/2,maxamp};
    }
};

void IRQHandler::IRQ_handler_local()
{
    for (size_t i = 0; i < n_devices; i++)
    {
        if (callbacks[i]())
        {
            break;
        }
    }
}

inline void AudioDevice::arm_dma_channels_chained_irq()
{

    auto conf_buffer = dma_buffer.get_default_config();

    channel_config_set_read_increment(&conf_buffer, true);
    channel_config_set_write_increment(&conf_buffer, false);
    channel_config_set_transfer_data_size(&conf_buffer, DMA_SIZE_32);
    channel_config_set_dreq(&conf_buffer, pio.get_dreq_tx());

    channel_config_set_chain_to(&conf_buffer, dma_control.get_channel());

    dma_buffer.configure(
        conf_buffer,
        pio.get_tx_fifo_addr(),
        buffer.A,
        BUFFSIZE,
        false
    );

    auto conf_control = dma_control.get_default_config();

    channel_config_set_read_increment(&conf_control, false);
    channel_config_set_write_increment(&conf_control, false);
    channel_config_set_transfer_data_size(&conf_control, DMA_SIZE_32);

    dma_control.configure(
        conf_control,
        dma_buffer.get_al3_read_addr_trig_reg(),
        &buffer_start_pointer,
        1,
        false
    );


    dma_control.set_irq0_enabled(true);

    irq_set_exclusive_handler(DMA_IRQ_0, IRQHandler::IRQ_handler_static);
    irq_set_enabled(DMA_IRQ_0, true);

}

inline void AudioDevice::init_buffers()
{
    for (size_t i = 0; i < BUFFSIZE; i++)
    {
        buffer.A[i] = 0;
        buffer.B[i] = 0;
        buffer.C[i] = 0;
    }

    buffer_ptrs.A = buffer.A;
    buffer_ptrs.B = buffer.B;
    buffer_ptrs.C = buffer.C;
    
}

AudioDevice::AudioDevice()
{

}

inline AudioDevice::AudioDevice(uint dataPin, uint lckPin, DeviceMode mode_, uint channels, IRQHandler * irq_h_ptr)
{
    pins.data       =   dataPin;
    pins.lck        =    lckPin;
    mode            =     mode_;
    channel_num     =  channels;
    IRQ_handler_ptr = irq_h_ptr;
    
    IRQ_handler_ptr->registerDevice(this, &AudioDevice::confirm_interrupt);
}

AudioDevice::~AudioDevice()
{

}

inline AudioDevice AudioDevice::createAudioDevice(uint dataPin, uint lckPin, DeviceMode mode, uint channels)
{
    return AudioDevice();
}

inline void AudioDevice::setSource(AudioSource *source_)
{
    source = source_;
    useCallback = true;
}

inline bool AudioDevice::initialize()
{
    auto pio_handle = PioHandler::acquire(&audio_device_program, audio_device_program_get_default_config);

    if (!pio_handle.has_value())
    {
        return false;
    }
    
    pio = std::move(pio_handle.value());

    pio.set_clkdiv_int_frac8(13, 1);
    pio.set_out_shift(false, true, 32);
    pio.set_wrap(audio_device_wrap_target, audio_device_wrap);

    pio.set_out_pins(pins.data);
    pio.set_sideset_pins(pins.lck, 2, true);

    pio.init();

    init_buffers();

    //the DMA will start reading from buffer A, so we prepare buffer B
    buffer_start_pointer = buffer.C;

    auto dma_buf = DmaHandler::acquire();
    auto dma_cont = DmaHandler::acquire();

    if (!dma_buf.has_value()) return false;
    if (!dma_cont.has_value()) return false;
    
    dma_buffer = std::move(dma_buf.value());
    dma_control = std::move(dma_cont.value());

    arm_dma_channels_chained_irq();

    dma_buffer.start();

    pio.set_enabled(true);

    return true;
}

inline bool AudioDevice::update() //!!!!!!!!!!!!CLEAN UP BUFFER SWAPPING AND MAKE ONLY TWO BUFFERS!!!!!!
{
    if (buffer_update_flag)
    {
        // Since we start with buffer A loaded into the dma we should load in buffer C as second and D as third, so C is always the next buffer
        uint32_t *tmp_ptr = buffer_ptrs.C;
        buffer_ptrs.C = buffer_ptrs.B;
        buffer_ptrs.B = buffer_ptrs.A;
        buffer_ptrs.A = tmp_ptr;

        buffer_start_pointer = buffer_ptrs.C;

        buffer_update_flag = false;

        if (useCallback)
        {
            source->audioCallback(AudioBuffer{buffer_ptrs.B, BUFFSIZE/2, SPS, maxamp});
        }

        return true;
    }    
    return false;
}

inline bool AudioDevice::confirm_interrupt()
{
    if (dma_control.check_irq0())
    {
        buffer_update_flag = true;
        return true;
    }
    return false;
}

inline void AudioDevice::writeAudio(int i, int16_t value, ChannelMode mode)
{
    if (mode == ChannelMode::LEFT)
    {
        buffer_ptrs.B[2*i] = int16_to_uint32(value);
    }
    else if (mode == ChannelMode::RIGHT)
    {
        buffer_ptrs.B[2*i + 1] = int16_to_uint32(value);
    }
    else
    {
        buffer_ptrs.B[2*i] = int16_to_uint32(value);
        buffer_ptrs.B[2*i + 1] = int16_to_uint32(value);
    }
    
}
